project:
  type: book
  output-dir: _book

book:
  title: "Data visualization with ggplot2"
  author: "Jesse Sadler"
  cover-image: ggplot2.png

  chapters:
    - index.qmd
    - rstudio-guide.qmd
    - grammar-of-graphics.qmd
    - content.qmd
    - resources.qmd

format:
  html:
    theme:
      - default
      - custom.scss
    toc: true
    code-link: true
    number-depth: 3
    highlight-style: arrow



