---
title: "Data visualization with ggplot2"
date: "2026-03-03"
---

## Welcome {.unnumbered}
This hands-on, participatory workshop is designed for those with basic R programming experience that are looking to take their data visualization skills to the next level. Join us to learn about making high-quality, reproducible data visualizations with [R](https://www.r-project.org/) and [ggplot2](https://ggplot2.tidyverse.org/). Attendees will practice making different kinds of plots, modifying color scales, and styling plots to make publication-ready visualizations.

The workshop is open to anyone, but learners should be familiar with programming in R and ggplot2 equivalent to the [Intro to R and RStudio](https://calendar.lib.vt.edu/event/16053032) and [Data wrangling and visualization with R](https://calendar.lib.vt.edu/event/16053104) workshops or one of the [Carpentries lessons](https://carpentries.org/lessons/) on R.

### Learning outcomes {.unnumbered}
- Be able to make various types of plots with ggplot2, including barplots, histograms, boxplots, and scatterplots.
- Learn to modify standard scales in ggplot2 and use various color palettes.
- Gain familiarity with different ways to highlight and annotate data within plots.
- Use ggplot2’s theming system to style plots in preparation for publication.

## Setup {.unnumbered}

Please download R and RStudio before the workshop. If you already have R and RStudio installed, check for updates in [RStudio](https://posit.co/download/rstudio-desktop/) and make sure you have a recent version of [R](https://cran.r-project.org/). The current version of R as of 3 March 2026 is 4.5.2. Please make sure that you have **at least version 4.3** or greater.

- [Download R](https://cran.r-project.org/)
- [Download RStudio](https://posit.co/download/rstudio-desktop/)

## Install packages for the workshop {.unnumbered}

There are a large number of packages that extend the capabilities of ggplot2. We will use some of the more widely used ones in this workshop and the materials will point to other options. You can install the packages in the console in RStudio or using the Packages tab in the bottom-right pane in RStudio.

```{r}
#| eval: false
install.packages(c("tidyverse", "palmerpenguins", "ggrepel", "paletteer",
                   "systemfonts", "marquee", "patchwork"))
```

- [tidyverse](https://tidyverse.org): Tidyverse collection of packages, including [ggplot2](https://ggplot2.tidyverse.org).
- [palmerpenguins](https://allisonhorst.github.io/palmerpenguins/): Data for the workshop.
- [ggrepel](https://ggrepel.slowkow.com): To help anotate plots.
- [paletteer](https://emilhvitfeldt.github.io/paletteer/): Large collection of color palettes.
- [systemfonts](https://systemfonts.r-lib.org): Enable R to find installed fonts.
- [marquee](https://marquee.r-lib.org): Enable text formatting in ggplot2 using Markdown.
- [patwork](https://patchwork.data-imaginist.com/index.html): Combine multiple plots into a single graphic.
